/**
 * index.ts — 상수 통합 re-export
 */

export {
  GRID_UNIT,
  HEIGHT_STEP,
  MAX_HEIGHT,
  MIN_HEIGHT,
  MAP_SIZE_PRESETS,
  DEFAULT_MAP_SIZE,
  MAX_UNDO_DEPTH,
  DEFAULT_BRUSH_SIZE,
  MIN_BRUSH_SIZE,
  MAX_BRUSH_SIZE,
  DRAG_THROTTLE_MS,
  SCULPT_DRAG_THRESHOLD,
  CAMERA_PAN_SPEED,
  GRID_OVERLAY_Y_OFFSET,
  CURSOR_Y_OFFSET,
} from './grid.ts';

export {
  SEGMENT_LENGTH,
  SLOPE_HEIGHT_DELTA,
  DEFAULT_STATION_LENGTH,
  SNAP_RADIUS,
  COLLISION_MIN_DISTANCE,
  MAX_SEGMENTS_PER_RIDE,
  STATION_ROTATION_STEP,
  SUPPORT_MIN_HEIGHT,
  SUPPORT_RADIUS,
  TRACK_CLEARANCE_RADIUS,
  TUNNEL_RADIUS,
  TUNNEL_ARCH_SEGMENTS,
  TUNNEL_DETECTION_MARGIN,
} from './track.ts';

export {
  GRAVITY,
  INITIAL_LAUNCH_SPEED,
  CHAIN_LIFT_SPEED,
  BRAKE_DECELERATION,
  BRAKE_TARGET_SPEED,
  BOOSTER_ACCELERATION,
  BOOSTER_TARGET_SPEED,
  MIN_SPEED,
  MAX_SPEED,
  ARC_LENGTH_SAMPLES,
  SPEED_SYNC_INTERVAL_MS,
  MAX_DELTA_TIME,
  FIRST_PERSON_HEIGHT,
  THIRD_PERSON_BEHIND,
  THIRD_PERSON_ABOVE,
  CAR_SPACING,
} from './physics.ts';
