/**
 * index.ts — 상수 통합 re-export
 */

export {
  GRID_UNIT,
  HEIGHT_STEP,
  MAX_HEIGHT,
  MIN_HEIGHT,
  MAP_SIZE_PRESETS,
  DEFAULT_MAP_SIZE,
  MAX_UNDO_DEPTH,
  DEFAULT_BRUSH_SIZE,
  MIN_BRUSH_SIZE,
  MAX_BRUSH_SIZE,
  DRAG_THROTTLE_MS,
  SCULPT_DRAG_THRESHOLD,
  CAMERA_PAN_SPEED,
  GRID_OVERLAY_Y_OFFSET,
  CURSOR_Y_OFFSET,
} from './grid.ts';

export {
  SEGMENT_LENGTH,
  SLOPE_HEIGHT_DELTA,
  DEFAULT_STATION_LENGTH,
  SNAP_RADIUS,
  COLLISION_MIN_DISTANCE,
  MAX_SEGMENTS_PER_RIDE,
  STATION_ROTATION_STEP,
} from './track.ts';
