/**
 * index.ts — 상수 통합 re-export
 */

export {
  GRID_UNIT,
  HEIGHT_STEP,
  MAX_HEIGHT,
  MIN_HEIGHT,
  MAP_SIZE_PRESETS,
  DEFAULT_MAP_SIZE,
  MAX_UNDO_DEPTH,
  DEFAULT_BRUSH_SIZE,
  MIN_BRUSH_SIZE,
  MAX_BRUSH_SIZE,
  DRAG_THROTTLE_MS,
  SCULPT_DRAG_THRESHOLD,
  CAMERA_PAN_SPEED,
  GRID_OVERLAY_Y_OFFSET,
  CURSOR_Y_OFFSET,
} from './grid.ts';
